### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by seohee0925** [seohee0925/labproject-data#1]
- [ ] csv 한글사이트 크롤링 합치기
- [ ] 태그 Okt로 분석 -> 원핫 인코딩 -> 클러스터링 -> 기간별 최빈어 뽑기
- [ ] 데이터셋 간 TF-IDF
- [ ] 깃허브 업로드 및 파일 구조 정리
